version: '3.3'
services:
  prometheus:
    container_name: prometheus
    image: 'prom/prometheus:v2.14.0'
    ports:
      - '9090:9090'
    volumes:
      - './prometheus.yaml:/etc/prometheus/prometheus.yml'
    command: '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - monitoring_net

  grafana:
    container_name: grafana
    image: 'grafana/grafana:6.5.0'
    ports:
      - '3000:3000'
    networks:
      - monitoring_net

networks:
  monitoring_net:
    driver: bridge
